import { storage } from "../../../shared/lib/storage";

export const USERS_STORAGE_KEY = "velzon_demo_users";

export const DEFAULT_USERS = [
  {
    id: "user-1",
    name: "Anna Adame",
    email: "anna@example.com",
    phone: "+8801710001111",
    avatar: "/assets/images/users/avatar-1.jpg",
    role: "Admin",
    address: "Dhaka, Bangladesh",
    status: "Active",
  },
  {
    id: "user-2",
    name: "Karim Hasan",
    email: "karim@example.com",
    phone: "+8801720002222",
    avatar: "/assets/images/users/avatar-2.jpg",
    role: "Manager",
    address: "Chattogram, Bangladesh",
    status: "Active",
  },
  {
    id: "user-3",
    name: "Sadia Khan",
    email: "sadia@example.com",
    phone: "+8801730003333",
    avatar: "/assets/images/users/avatar-3.jpg",
    role: "Support",
    address: "Khulna, Bangladesh",
    status: "Inactive",
  },
  {
    id: "user-4",
    name: "Fahim Rahman",
    email: "fahim@example.com",
    phone: "+8801740004444",
    avatar: "/assets/images/users/avatar-4.jpg",
    role: "Viewer",
    address: "Sylhet, Bangladesh",
    status: "Active",
  },
  {
    id: "user-5",
    name: "Nusrat Jahan",
    email: "nusrat@example.com",
    phone: "+8801750005555",
    avatar: "/assets/images/users/avatar-5.jpg",
    role: "Support",
    address: "Rajshahi, Bangladesh",
    status: "Active",
  },
  {
    id: "user-6",
    name: "Rafiul Islam",
    email: "rafiul@example.com",
    phone: "+8801760006666",
    avatar: "/assets/images/users/avatar-6.jpg",
    role: "Manager",
    address: "Mymensingh, Bangladesh",
    status: "Active",
  },
  {
    id: "user-7",
    name: "Tania Akter",
    email: "tania@example.com",
    phone: "+8801770007777",
    avatar: "/assets/images/users/avatar-7.jpg",
    role: "Support",
    address: "Barishal, Bangladesh",
    status: "Inactive",
  },
  {
    id: "user-8",
    name: "Imran Hossain",
    email: "imran@example.com",
    phone: "+8801780008888",
    avatar: "/assets/images/users/avatar-8.jpg",
    role: "Viewer",
    address: "Rangpur, Bangladesh",
    status: "Active",
  },
  {
    id: "user-9",
    name: "Mahi Chowdhury",
    email: "mahi@example.com",
    phone: "+8801790009999",
    avatar: "/assets/images/users/avatar-1.jpg",
    role: "Admin",
    address: "Dhaka, Bangladesh",
    status: "Active",
  },
  {
    id: "user-10",
    name: "Sabbir Ahmed",
    email: "sabbir@example.com",
    phone: "+8801810001010",
    avatar: "/assets/images/users/avatar-2.jpg",
    role: "Manager",
    address: "Gazipur, Bangladesh",
    status: "Active",
  },
  {
    id: "user-11",
    name: "Mariam Sultana",
    email: "mariam@example.com",
    phone: "+8801820001111",
    avatar: "/assets/images/users/avatar-3.jpg",
    role: "Support",
    address: "Narayanganj, Bangladesh",
    status: "Active",
  },
  {
    id: "user-12",
    name: "Saif Rahman",
    email: "saif@example.com",
    phone: "+8801830001212",
    avatar: "/assets/images/users/avatar-4.jpg",
    role: "Viewer",
    address: "Cumilla, Bangladesh",
    status: "Inactive",
  },
  {
    id: "user-13",
    name: "Farzana Haque",
    email: "farzana@example.com",
    phone: "+8801840001313",
    avatar: "/assets/images/users/avatar-5.jpg",
    role: "Manager",
    address: "Noakhali, Bangladesh",
    status: "Active",
  },
  {
    id: "user-14",
    name: "Tamim Iqbal",
    email: "tamim@example.com",
    phone: "+8801850001414",
    avatar: "/assets/images/users/avatar-6.jpg",
    role: "Support",
    address: "Feni, Bangladesh",
    status: "Active",
  },
  {
    id: "user-15",
    name: "Lamia Nawar",
    email: "lamia@example.com",
    phone: "+8801860001515",
    avatar: "/assets/images/users/avatar-7.jpg",
    role: "Viewer",
    address: "Jessore, Bangladesh",
    status: "Active",
  },
  {
    id: "user-16",
    name: "Rakib Hasan",
    email: "rakib@example.com",
    phone: "+8801870001616",
    avatar: "/assets/images/users/avatar-8.jpg",
    role: "Manager",
    address: "Bogura, Bangladesh",
    status: "Inactive",
  },
  {
    id: "user-17",
    name: "Sharmin Ara",
    email: "sharmin@example.com",
    phone: "+8801880001717",
    avatar: "/assets/images/users/avatar-1.jpg",
    role: "Support",
    address: "Kushtia, Bangladesh",
    status: "Active",
  },
  {
    id: "user-18",
    name: "Nayeem Hasan",
    email: "nayeem@example.com",
    phone: "+8801890001818",
    avatar: "/assets/images/users/avatar-2.jpg",
    role: "Viewer",
    address: "Dinajpur, Bangladesh",
    status: "Active",
  },
  {
    id: "user-19",
    name: "Arifa Khan",
    email: "arifa@example.com",
    phone: "+8801910001919",
    avatar: "/assets/images/users/avatar-3.jpg",
    role: "Support",
    address: "Pabna, Bangladesh",
    status: "Active",
  },
  {
    id: "user-20",
    name: "Shahriar Islam",
    email: "shahriar@example.com",
    phone: "+8801920002020",
    avatar: "/assets/images/users/avatar-4.jpg",
    role: "Manager",
    address: "Tangail, Bangladesh",
    status: "Inactive",
  },
  {
    id: "user-21",
    name: "Sadia Noor",
    email: "sadianoor@example.com",
    phone: "+8801930002121",
    avatar: "/assets/images/users/avatar-5.jpg",
    role: "Viewer",
    address: "Faridpur, Bangladesh",
    status: "Active",
  },
  {
    id: "user-22",
    name: "Mahmudul Hasan",
    email: "mahmudul@example.com",
    phone: "+8801940002222",
    avatar: "/assets/images/users/avatar-6.jpg",
    role: "Support",
    address: "Brahmanbaria, Bangladesh",
    status: "Active",
  },
  {
    id: "user-23",
    name: "Tasnim Jubaer",
    email: "tasnim@example.com",
    phone: "+8801950002323",
    avatar: "/assets/images/users/avatar-7.jpg",
    role: "Manager",
    address: "Chuadanga, Bangladesh",
    status: "Active",
  },
  {
    id: "user-24",
    name: "Nabil Rahat",
    email: "nabil@example.com",
    phone: "+8801960002424",
    avatar: "/assets/images/users/avatar-8.jpg",
    role: "Viewer",
    address: "Meherpur, Bangladesh",
    status: "Inactive",
  },
  {
    id: "user-25",
    name: "Sifat Karim",
    email: "sifat@example.com",
    phone: "+8801970002525",
    avatar: "/assets/images/users/avatar-1.jpg",
    role: "Support",
    address: "Jhenaidah, Bangladesh",
    status: "Active",
  },
  {
    id: "user-26",
    name: "Rubaiya Akter",
    email: "rubaiya@example.com",
    phone: "+8801980002626",
    avatar: "/assets/images/users/avatar-2.jpg",
    role: "Manager",
    address: "Magura, Bangladesh",
    status: "Active",
  },
  {
    id: "user-27",
    name: "Adnan Mahin",
    email: "adnan@example.com",
    phone: "+8801990002727",
    avatar: "/assets/images/users/avatar-3.jpg",
    role: "Viewer",
    address: "Satkhira, Bangladesh",
    status: "Active",
  },
  {
    id: "user-28",
    name: "Proma Chowdhury",
    email: "proma@example.com",
    phone: "+8801711002828",
    avatar: "/assets/images/users/avatar-4.jpg",
    role: "Support",
    address: "Bagerhat, Bangladesh",
    status: "Inactive",
  },
  {
    id: "user-29",
    name: "Irfan Ahmed",
    email: "irfan@example.com",
    phone: "+8801712002929",
    avatar: "/assets/images/users/avatar-5.jpg",
    role: "Manager",
    address: "Narsingdi, Bangladesh",
    status: "Active",
  },
  {
    id: "user-30",
    name: "Jannatul Ferdous",
    email: "jannatul@example.com",
    phone: "+8801713003030",
    avatar: "/assets/images/users/avatar-6.jpg",
    role: "Viewer",
    address: "Netrokona, Bangladesh",
    status: "Active",
  },
];

function normalizeUsers(raw) {
  if (!Array.isArray(raw) || !raw.length) return DEFAULT_USERS;

  return raw.map((user) => ({
    id: user?.id || `user-${Math.random().toString(36).slice(2, 9)}`,
    name: user?.name?.trim() || "",
    email: user?.email?.trim() || "",
    phone: user?.phone?.trim() || "",
    avatar: user?.avatar?.trim() || "/assets/images/users/avatar-1.jpg",
    role: user?.role?.trim() || "",
    address: user?.address?.trim() || "",
    status: user?.status === "Inactive" ? "Inactive" : "Active",
  }));
}

export function loadUsers() {
  const normalized = normalizeUsers(storage.get(USERS_STORAGE_KEY));

  if (normalized.length >= DEFAULT_USERS.length) return normalized;

  const existingById = new Set(normalized.map((user) => user.id));
  const missing = DEFAULT_USERS.filter((user) => !existingById.has(user.id));
  const merged = [...normalized, ...missing];
  storage.set(USERS_STORAGE_KEY, merged);
  return merged;
}

export function saveUsers(users) {
  storage.set(USERS_STORAGE_KEY, normalizeUsers(users));
}
